### ISSUE TITLE
Build project with images assets

### ISSUE THREAD

**Issue by ojuliomiguel** [ojuliomiguel/pdf-together#1]
- [x] Build the layout project in new netbeans project
- [x] Testing the builder process and the jar file
- [x] Fix build project

**Comment by ojuliomiguel** [comment]
## Tested the .jar file built on macOS in another SO (Windows)

![image](https://github.com/ojuliomiguel/pdf-together/assets/37316841/392e6ffb-a4d5-4938-b82b-aa9dce0aa78a)

**Comment by ojuliomiguel** [comment]
# The fix build process:

Maven expects to find resources in `src/main/resources` (by default). Despite the resources folder is set in correct place in the project the configuration to maven see the resources was wrong:


```xml
<configuration>
  <resources>
    <resource>
      <directory>src/main</directory> <!-- wrong default dir -->
        <includes>
	  <include>**/*.png</include> 
	</includes>
     </resource>
  </resources>
</configuration>
```

[Helpful content - Including images in a Java Swing Maven application](https://www.youtube.com/watch?v=U_9qrcVq7T4)

**Comment by elyosemite** [comment]
Parabéns, mano! Tá ficando incrível!!!
